#include "recommend.h"
#include <string.h>
/* O(I^2), with I bounded by FG_INTERESTS */
static int shared_interests(const FGUser*a,const FGUser*b){int n=0;for(int i=0;i<a->interest_count;i++)for(int j=0;j<b->interest_count;j++)if(strcmp(a->interests[i],b->interests[j])==0){n++;break;}return n;}
/* O(B), with B bounded by 128 */
static int has_id(const int*a,int n,int id){for(int i=0;i<n;i++)if(a[i]==id)return 1;return 0;}
/* O(V+E + C*(d log d + K log C)), where C is candidates, K is result limit */
size_t recommend_for_user(const Graph*g,const FGUser*u,size_t count,int source,int max_distance,int min_mutual,int limit,Recommendation*out){if(!g||!u||!out||source<0||(size_t)source>=count||limit<=0)return 0;BFSResult b;if(!bfs_run(g,source,max_distance,&b))return 0;MaxHeap h;heap_init(&h);for(size_t id=0;id<count&&id<g->n;id++){int d=b.dist[id];if((int)id==source||d<2||d>max_distance||d<0||are_friends(g,source,(int)id)||has_id(u[source].blocked,u[source].blocked_count,(int)id)||has_id(u[id].blocked,u[id].blocked_count,source))continue;int mc=(int)mutual_friends(g,source,(int)id,NULL,0);if(mc<min_mutual)continue;int score=mc*10+(d==2?20:8)+shared_interests(&u[source],&u[id])*5-(has_id(u[source].declined,u[source].declined_count,(int)id)?15:0);heap_push(&h,(HeapItem){(int)id,score});}
size_t got=0;while(got<(size_t)limit&&h.len){HeapItem it;heap_pop(&h,&it);int id=it.id;Recommendation*r=&out[got];memset(r,0,sizeof(*r));r->id=id;r->score=it.score;r->distance=b.dist[id];r->mutual_count=(int)mutual_friends(g,source,id,r->mutual_ids,128);r->mutual_points=r->mutual_count*10;r->distance_points=r->distance==2?20:8;r->interest_points=shared_interests(&u[source],&u[id])*5;r->penalty=has_id(u[source].declined,u[source].declined_count,id)?15:0;int path[128],n=0,v=id;while(v>=0&&n<128){path[n++]=v;if(v==source)break;v=b.parent[v];}r->path_len=n;for(int j=0;j<n;j++)r->path[j]=path[n-1-j];got++;}heap_free(&h);bfs_free(&b);return got;}
